import { Injectable } from '@angular/core';
import { SegmentDefinition, ComponentDefinition } from '../models/hl7.model';

@Injectable({
  providedIn: 'root',
})
export class Hl7ParserService {
  private readonly SEGMENT_DEFS: { [key: string]: SegmentDefinition } = {
    MSH: {
      name: 'Message Header',
      fields: [
        'Field Separator',
        'Encoding Characters',
        'Sending Application',
        'Sending Facility',
        'Receiving Application',
        'Receiving Facility',
        'Date/Time of Message',
        'Security',
        'Message Type',
        'Message Control ID',
        'Processing ID',
        'Version ID',
        'Sequence Number',
        'Continuation Pointer',
        'Accept Acknowledgment Type',
        'Application Acknowledgment Type',
        'Country Code',
        'Character Set',
        'Principal Language',
        'Alt Char Set Handling',
        'Message Profile Identifier',
      ],
    },
    PID: {
      name: 'Patient Identification',
      fields: [
        'Set ID',
        'Patient ID',
        'Patient Identifier List',
        'Alternate Patient ID',
        'Patient Name',
        "Mother's Maiden Name",
        'Date/Time of Birth',
        'Administrative Sex',
        'Patient Alias',
        'Race',
        'Patient Address',
        'County Code',
        'Phone Number - Home',
        'Phone Number - Business',
        'Primary Language',
        'Marital Status',
        'Religion',
        'Patient Account Number',
        'SSN Number',
        "Driver's License Number",
        "Mother's Identifier",
        'Ethnic Group',
        'Birth Place',
        'Multiple Birth Indicator',
        'Birth Order',
        'Citizenship',
        'Veterans Military Status',
        'Nationality',
        'Patient Death Date/Time',
        'Patient Death Indicator',
        'Identity Unknown Indicator',
        'Identity Reliability Code',
        'Last Update Date/Time',
        'Last Update Facility',
        'Species Code',
        'Breed Code',
        'Strain',
        'Production Class Code',
        'Tribal Citizenship',
        'Patient Telecom Info',
      ],
    },
    PV1: {
      name: 'Patient Visit',
      fields: [
        'Set ID',
        'Patient Class',
        'Assigned Patient Location',
        'Admission Type',
        'Preadmit Number',
        'Prior Patient Location',
        'Attending Doctor',
        'Referring Doctor',
        'Consulting Doctor',
        'Hospital Service',
        'Temporary Location',
        'Preadmit Test Indicator',
        'Re-admission Indicator',
        'Admit Source',
        'Ambulatory Status',
        'VIP Indicator',
        'Admitting Doctor',
        'Patient Type',
        'Visit Number',
        'Financial Class',
        'Charge Price Indicator',
        'Courtesy Code',
        'Credit Rating',
        'Contract Code',
        'Contract Effective Date',
        'Contract Amount',
        'Contract Period',
        'Interest Code',
        'Transfer to Bad Debt Code',
        'Transfer to Bad Debt Date',
        'Bad Debt Agency Code',
        'Bad Debt Transfer Amount',
        'Bad Debt Recovery Amount',
        'Delete Account Indicator',
        'Delete Account Date',
        'Discharge Disposition',
        'Discharged to Location',
        'Diet Type',
        'Servicing Facility',
        'Bed Status',
        'Account Status',
        'Pending Location',
        'Prior Temporary Location',
        'Admit Date/Time',
        'Discharge Date/Time',
        'Current Patient Balance',
        'Total Charges',
        'Total Adjustments',
        'Total Payments',
        'Alternate Visit ID',
        'Visit Indicator',
      ],
    },
    OBR: {
      name: 'Observation Request',
      fields: [
        'Set ID',
        'Placer Order Number',
        'Filler Order Number',
        'Universal Service Identifier',
        'Priority',
        'Requested Date/Time',
        'Observation Date/Time',
        'Observation End Date/Time',
        'Collection Volume',
        'Collector Identifier',
        'Specimen Action Code',
        'Danger Code',
        'Relevant Clinical Info',
        'Specimen Received Date/Time',
        'Specimen Source',
        'Ordering Provider',
        'Order Callback Phone Number',
        'Placer Field 1',
        'Placer Field 2',
        'Filler Field 1',
        'Filler Field 2',
        'Results Rpt/Status Chng Date/Time',
        'Charge to Practice',
        'Diagnostic Service Section ID',
        'Result Status',
        'Parent Result',
        'Quantity/Timing',
        'Result Copies To',
        'Parent',
        'Transportation Mode',
        'Reason for Study',
        'Principal Result Interpreter',
        'Assistant Result Interpreter',
        'Technician',
        'Transcriptionist',
        'Scheduled Date/Time',
        'Number of Sample Containers',
        'Transport Logistics',
        "Collector's Comment",
        'Transport Arrangement Responsibility',
        'Transport Arranged',
        'Escort Required',
        'Planned Patient Transport Comment',
        'Procedure Code',
        'Procedure Code Modifier',
      ],
    },
    OBX: {
      name: 'Observation Result',
      fields: [
        'Set ID',
        'Value Type',
        'Observation Identifier',
        'Observation Sub-ID',
        'Observation Value',
        'Units',
        'References Range',
        'Interpretation Codes',
        'Probability',
        'Nature of Abnormal Test',
        'Observation Result Status',
        'Effective Date of Reference Range',
        'User Defined Access Checks',
        'Date/Time of Observation',
        "Producer's ID",
        'Responsible Observer',
        'Observation Method',
        'Equipment Instance Identifier',
        'Date/Time of Analysis',
      ],
    },
    EVN: {
      name: 'Event Type',
      fields: [
        'Event Type Code',
        'Recorded Date/Time',
        'Date/Time Planned Event',
        'Event Reason Code',
        'Operator ID',
        'Event Occurred',
        'Event Facility',
      ],
    },
    NK1: {
      name: 'Next of Kin',
      fields: [
        'Set ID',
        'Name',
        'Relationship',
        'Address',
        'Phone Number',
        'Business Phone Number',
        'Contact Role',
        'Start Date',
        'End Date',
        'Job Title',
        'Job Code/Class',
        'Employee Number',
        'Organization Name',
        'Marital Status',
        'Administrative Sex',
        'Date/Time of Birth',
        'Living Dependency',
        'Ambulatory Status',
        'Citizenship',
        'Primary Language',
        'Living Arrangement',
        'Publicity Code',
        'Protection Indicator',
        'Student Indicator',
        'Religion',
        "Mother's Maiden Name",
        'Nationality',
        'Ethnic Group',
        'Contact Reason',
        "Contact Person's Name",
        "Contact Person's Phone",
        "Contact Person's Address",
      ],
    },
    AL1: {
      name: 'Patient Allergy Information',
      fields: [
        'Set ID',
        'Allergen Type Code',
        'Allergen Code/Description',
        'Allergy Severity Code',
        'Allergy Reaction Code',
        'Identification Date',
      ],
    },
    DG1: {
      name: 'Diagnosis',
      fields: [
        'Set ID',
        'Diagnosis Coding Method',
        'Diagnosis Code',
        'Diagnosis Description',
        'Diagnosis Date/Time',
        'Diagnosis Type',
        'Major Diagnostic Category',
        'Diagnostic Related Group',
        'DRG Approval Indicator',
        'DRG Grouper Review Code',
        'Outlier Type',
        'Outlier Days',
        'Outlier Cost',
        'Grouper Version',
        'Diagnosis Priority',
        'Diagnosing Clinician',
        'Diagnosis Classification',
        'Confidential Indicator',
        'Attestation Date/Time',
        'Diagnosis Identifier',
        'Diagnosis Action Code',
      ],
    },
    NTE: {
      name: 'Notes and Comments',
      fields: [
        'Set ID',
        'Source of Comment',
        'Comment',
        'Comment Type',
        'Entered By',
        'Entered Date/Time',
        'Effective Start Date',
        'Expiration Date',
      ],
    },
    MSA: {
      name: 'Message Acknowledgment',
      fields: [
        'Acknowledgment Code',
        'Message Control ID',
        'Text Message',
        'Expected Sequence Number',
        'Delayed Acknowledgment Type',
        'Error Condition',
      ],
    },
    ERR: {
      name: 'Error',
      fields: [
        'Error Code and Location',
        'Error Location',
        'HL7 Error Code',
        'Severity',
        'Application Error Code',
        'Application Error Parameter',
        'Diagnostic Information',
        'User Message',
        'Inform Person Indicator',
        'Override Type',
        'Override Reason Code',
        'Help Desk Contact Point',
      ],
    },
    IN1: {
      name: 'Insurance',
      fields: [
        'Set ID',
        'Insurance Plan ID',
        'Insurance Company ID',
        'Insurance Company Name',
        'Insurance Company Address',
        'Insurance Co Contact Person',
        'Insurance Co Phone Number',
        'Group Number',
        'Group Name',
        "Insured's Group Emp ID",
        "Insured's Group Emp Name",
        'Plan Effective Date',
        'Plan Expiration Date',
        'Authorization Information',
        'Plan Type',
        'Name of Insured',
        "Insured's Relationship to Patient",
        "Insured's Date of Birth",
        "Insured's Address",
        'Assignment of Benefits',
        'Coordination of Benefits',
        'Coord of Ben. Priority',
        'Notice of Admission Flag',
        'Notice of Admission Date',
        'Report of Eligibility Flag',
        'Report of Eligibility Date',
        'Release Information Code',
        'Pre-Admit Cert (PAC)',
        'Verification Date/Time',
        'Verification By',
        'Type of Agreement Code',
        'Billing Status',
        'Lifetime Reserve Days',
        'Delay Before L.R. Day',
        'Company Plan Code',
        'Policy Number',
      ],
    },
    PR1: {
      name: 'Procedures',
      fields: [
        'Set ID',
        'Procedure Coding Method',
        'Procedure Code',
        'Procedure Description',
        'Procedure Date/Time',
        'Procedure Functional Type',
        'Procedure Minutes',
        'Anesthesiologist',
        'Anesthesia Code',
        'Anesthesia Minutes',
        'Surgeon',
        'Procedure Practitioner',
        'Consent Code',
        'Procedure Priority',
        'Associated Diagnosis Code',
        'Procedure Code Modifier',
      ],
    },
    RXA: {
      name: 'Pharmacy/Treatment Administration',
      fields: [
        'Give Sub-ID Counter',
        'Administration Sub-ID Counter',
        'Date/Time Start of Administration',
        'Date/Time End of Administration',
        'Administered Code',
        'Administered Amount',
        'Administered Units',
        'Administered Dosage Form',
        'Administration Notes',
        'Administering Provider',
        'Administered-at Location',
        'Administered Per (Time Unit)',
        'Administered Strength',
        'Administered Strength Units',
        'Substance Lot Number',
        'Substance Expiration Date',
        'Substance Manufacturer Name',
        'Substance/Treatment Refusal Reason',
        'Indication',
        'Completion Status',
        'Action Code',
        'System Entry Date/Time',
      ],
    },
  };

  private readonly COMP_DEFS: ComponentDefinition = {
    'PID-5': [
      'Family Name',
      'Given Name',
      'Middle Initial/Name',
      'Suffix',
      'Prefix',
      'Degree',
    ],
    'PID-6': [
      'Family Name',
      'Given Name',
      'Middle Initial/Name',
      'Suffix',
      'Prefix',
      'Degree',
    ],
    'PID-11': [
      'Street Address',
      'Other Designation',
      'City',
      'State/Province',
      'ZIP/Postal Code',
      'Country',
      'Address Type',
      'Other Geographic Designation',
    ],
    'PID-3': [
      'ID Number',
      'Check Digit',
      'Check Digit Scheme',
      'Assigning Authority',
      'Identifier Type Code',
      'Assigning Facility',
    ],
    'MSH-9': ['Message Code', 'Trigger Event', 'Message Structure'],
    'MSH-3': ['Namespace ID', 'Universal ID', 'Universal ID Type'],
    'MSH-4': ['Namespace ID', 'Universal ID', 'Universal ID Type'],
    'OBX-3': [
      'Identifier',
      'Text',
      'Coding System',
      'Alt. Identifier',
      'Alt. Text',
      'Alt. Coding System',
    ],
    'OBX-6': ['Identifier', 'Text', 'Coding System'],
    'OBR-4': [
      'Identifier',
      'Text',
      'Coding System',
      'Alt. Identifier',
      'Alt. Text',
      'Alt. Coding System',
    ],
    'OBR-16': [
      'ID Number',
      'Family Name',
      'Given Name',
      'Middle Name',
      'Suffix',
      'Prefix',
      'Degree',
      'Source Table',
      'Assigning Authority',
    ],
    'PV1-3': [
      'Point of Care',
      'Room',
      'Bed',
      'Facility',
      'Location Status',
      'Person Location Type',
      'Building',
      'Floor',
      'Location Description',
    ],
    'PV1-7': [
      'ID Number',
      'Family Name',
      'Given Name',
      'Middle Name',
      'Suffix',
      'Prefix',
      'Degree',
      'Source Table',
      'Assigning Authority',
    ],
    'PV1-8': [
      'ID Number',
      'Family Name',
      'Given Name',
      'Middle Name',
      'Suffix',
      'Prefix',
      'Degree',
      'Source Table',
      'Assigning Authority',
    ],
    'NK1-2': [
      'Family Name',
      'Given Name',
      'Middle Name',
      'Suffix',
      'Prefix',
      'Degree',
    ],
    'NK1-4': [
      'Street Address',
      'Other Designation',
      'City',
      'State',
      'ZIP',
      'Country',
      'Address Type',
    ],
  };

  constructor() {}

  getSegmentDefinition(segmentName: string): SegmentDefinition {
    return (
      this.SEGMENT_DEFS[segmentName] || {
        name: 'Custom / Unknown Segment',
        fields: [],
      }
    );
  }

  getComponentDefinition(fieldNum: string): string[] {
    return this.COMP_DEFS[fieldNum] || [];
  }

  parseSegment(line: string): { segmentName: string; fields: string[] } | null {
    if (!line || !line.trim()) {
      return null;
    }

    const segName = line.substring(0, 3);
    if (!/^[A-Z]{2}[A-Z0-9]$/.test(segName) || line[3] !== '|') {
      return null;
    }

    let fields: string[];
    if (segName === 'MSH') {
      const sep = line[3] || '|';
      const rest = line.substring(4).split(sep);
      fields = [sep, ...rest];
    } else {
      fields = line.split('|').slice(1);
    }

    return { segmentName: segName, fields };
  }

  isDateField(fieldName: string): boolean {
    const lowerName = fieldName.toLowerCase();
    return (
      lowerName.includes('date') ||
      lowerName.includes('time') ||
      lowerName.includes('dt')
    );
  }

  formatHL7Date(dt: string): string {
    if (!dt || dt.length < 8) return '';

    const clean = dt.replace(/\D/g, '');
    if (clean.length < 8) return '';

    const year = clean.substr(0, 4);
    const month = clean.substr(4, 2);
    const day = clean.substr(6, 2);
    let formatted = `${month}/${day}/${year}`;

    if (clean.length >= 12) {
      const hour = clean.substr(8, 2);
      const minute = clean.substr(10, 2);
      const second = clean.length >= 14 ? clean.substr(12, 2) : '00';
      formatted += ` ${hour}:${minute}:${second}`;
    } else if (clean.length >= 10) {
      const hour = clean.substr(8, 2);
      formatted += ` ${hour}:00:00`;
    }

    return formatted;
  }
}
